from pathlib import Path

import pytest

from plutil.magic.cli import generate_plmagic_type_files, main
from plutil.magic.type_gen import (
    DataclassSourceBuilder,
    TypeSourceBuilder,
    write_plmagic_types_file,
)


def test_type_source_builder_builds_deduplicated_sorted_imports() -> None:
    builder = TypeSourceBuilder()
    builder.import_from("typing", "TypedDict", "Any")
    builder.import_from("typing", "Any", "Literal")
    builder.import_from("plutil.lenses", "QuestionData")
    builder.add(DataclassSourceBuilder("Example"))

    assert builder.build() == (
        "# AUTOMATICALLY GENERATED BY PLMAGIC #\n\n"
        "from plutil.lenses import QuestionData\n\n"
        "from typing import Any, Literal, TypedDict\n\n"
        "class Example:\n"
        "    pass\n"
    )


def test_type_source_builder_writes_built_source(tmp_path: Path) -> None:
    builder = TypeSourceBuilder()
    builder.add(DataclassSourceBuilder("Generated"))
    output_path = tmp_path / "generated.py"

    builder.write(output_path)

    assert output_path.read_text(encoding="utf-8") == builder.build()


def test_dataclass_source_builder_builds_annotated_class() -> None:
    builder = DataclassSourceBuilder("Preferences", ("TypedDict",))
    builder.add_field("mode", "Literal['a', 'b']")
    builder.add_field("count", "float", "1.0")

    assert builder.build() == (
        "class Preferences(TypedDict):\n"
        "    mode: Literal['a', 'b']\n"
        "    count: float\n"
        '    """Default value: `1.0`"""'
    )


def test_dataclass_source_builder_adds_empty_class_to_source() -> None:
    source = TypeSourceBuilder()

    source.add(DataclassSourceBuilder("Data", ("QuestionData[Preferences]",)))

    assert "class Data(QuestionData[Preferences]):\n    pass" in source.build()


def test_generate_plmagic_type_files_recursively(tmp_path: Path) -> None:
    first_question = tmp_path / "questions" / "first"
    second_question = tmp_path / "questions" / "second"
    ignored_question = tmp_path / "questions" / "ignored"
    for question in (first_question, second_question, ignored_question):
        question.mkdir(parents=True)
        (question / "info.json").write_text(
            '{"preferences": {"seed": {"type": "number"}}}', encoding="utf-8"
        )

    (first_question / "server.py").write_text(
        "from plutil import plmagic\n\n@plmagic\ndef generate(data): pass\n",
        encoding="utf-8",
    )
    # Multiple matching files in one question directory still produce one output.
    (first_question / "hooks.py").write_text(
        "import plutil\n\n@plutil.plmagic\ndef grade(data): pass\n",
        encoding="utf-8",
    )
    (second_question / "server.py").write_text(
        "@plmagic\nasync def parse(data): pass\n", encoding="utf-8"
    )
    (ignored_question / "server.py").write_text(
        "# @plmagic\ndef generate(data): pass\n", encoding="utf-8"
    )

    outputs = generate_plmagic_type_files(tmp_path)

    assert outputs == [
        first_question / "__plmagic_types__.py",
        second_question / "__plmagic_types__.py",
    ]
    assert all(
        path.read_text().startswith("# AUTOMATICALLY GENERATED") for path in outputs
    )
    assert not (ignored_question / "__plmagic_types__.py").exists()


def test_generate_plmagic_type_files_requires_companion_info_json(
    tmp_path: Path,
) -> None:
    (tmp_path / "server.py").write_text(
        "@plmagic\ndef generate(data): pass\n", encoding="utf-8"
    )

    with pytest.raises(FileNotFoundError, match="no companion info.json"):
        generate_plmagic_type_files(tmp_path)


def test_plmagic_types_main_prints_generated_paths(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    (tmp_path / "info.json").write_text(
        '{"preferences": {"seed": {"type": "number"}}}', encoding="utf-8"
    )
    (tmp_path / "server.py").write_text(
        "@plmagic\ndef generate(data): pass\n", encoding="utf-8"
    )

    assert main([str(tmp_path)]) == 0
    assert capsys.readouterr().out.strip() == str(tmp_path / "__plmagic_types__.py")


def test_write_plmagic_types_file_skips_all_empty_builders(tmp_path: Path) -> None:
    info_json_path = tmp_path / "info.json"
    info_json_path.write_text("{}", encoding="utf-8")

    assert not write_plmagic_types_file(info_json_path)
    assert not (tmp_path / "__plmagic_types__.py").exists()


def test_write_plmagic_types_file_overwrites_stale_file_with_empty_builders(
    tmp_path: Path,
) -> None:
    info_json_path = tmp_path / "info.json"
    info_json_path.write_text("{}", encoding="utf-8")
    output_path = tmp_path / "__plmagic_types__.py"
    output_path.write_text("class StalePreference: ...\n", encoding="utf-8")

    assert write_plmagic_types_file(info_json_path)
    assert "StalePreference" not in output_path.read_text(encoding="utf-8")
    assert "class Preferences(TypedDict):\n    pass" in output_path.read_text(
        encoding="utf-8"
    )
