from typing import Final

from . import rand
from .assumptions import AssumptionsTypedDict, check
from .common import (
    ExprInput,
    ExprLike,
    NumberLike,
    PlValue,
    SetInput,
    SetLike,
    SympyInput,
    SympyValue,
    clamp,
    count_in_latex,
    dbg,
    eq,
    getrec,
    is_trivial,
    json_to_sympy,
    latex,
    lim_latex,
    require_expr,
    setrec,
    sign,
    spint,
    to_expr,
    truncate_to_significant_digits,
)
from .functions import (
    eval_at,
    eval_at_,
    evalf_at,
    evalf_at_,
    rearrange_eqn,
)
from .lenses import (
    Data,
    NoPreferences,
    Question,
    SympyQuestion,
)
from .magic import (
    PlMagicError,
    main,
    plmagic,
)
from .partial_credit import (
    award_partial_credit,
    rule,
)
from .sets import (
    grade_sympy_set,
    reject_non_sympy_set_input,
)

__all__: Final[tuple[str, ...]] = (
    "AssumptionsTypedDict",
    "Data",
    "ExprInput",
    "ExprLike",
    "NoPreferences",
    "NumberLike",
    "PlMagicError",
    "PlValue",
    "Question",
    "SetInput",
    "SetLike",
    "SympyInput",
    "SympyQuestion",
    "SympyValue",
    "award_partial_credit",
    "check",
    "clamp",
    "count_in_latex",
    "dbg",
    "eq",
    "eval_at",
    "eval_at_",
    "evalf_at",
    "evalf_at_",
    "getrec",
    "grade_sympy_set",
    "is_trivial",
    "json_to_sympy",
    "latex",
    "lim_latex",
    "main",
    "plmagic",
    "rand",
    "rearrange_eqn",
    "reject_non_sympy_set_input",
    "require_expr",
    "rule",
    "setrec",
    "sign",
    "spint",
    "to_expr",
    "truncate_to_significant_digits",
)
