"""End-to-end tests for the ``plmagic-types`` command."""

import json
import os
from pathlib import Path

import pytest
from pyfakefs.fake_filesystem import FakeFilesystem

from plutil.__main__ import main as package_main
from plutil.magic.cli import main


def _create_question(
    fs: FakeFilesystem,
    path: str,
    *,
    server_source: str,
    preferences: dict[str, object] | None = None,
) -> None:
    fs.create_dir(path)
    fs.create_file(
        f"{path}/info.json",
        contents=json.dumps({"preferences": preferences or {}}),
    )
    fs.create_file(f"{path}/server.py", contents=server_source)


def test_cli_generates_types_for_all_plmagic_questions(
    fs: FakeFilesystem, capsys: pytest.CaptureFixture[str]
) -> None:
    _create_question(
        fs,
        "/course/questions/algebra/addition",
        server_source=(
            "from plutil import plmagic\n\n"
            "@plmagic\n"
            "def generate(data):\n"
            "    pass\n"
        ),
        preferences={
            "mode": {"enum": ["practice", "exam"], "default": "practice"},
            "showHints": {"type": "boolean", "default": True},
        },
    )
    _create_question(
        fs,
        "/course/questions/calculus/derivative",
        server_source=(
            "import plutil\n\n"
            "@plutil.plmagic\n"
            "async def grade(data):\n"
            "    pass\n"
        ),
        preferences={"seed": {"type": "number"}},
    )
    _create_question(
        fs,
        "/course/questions/statistics/aliased",
        server_source=(
            "from plutil.magic import plmagic as question_hook\n\n"
            "@question_hook()\n"
            "def generate(data):\n"
            "    pass\n"
        ),
        preferences={"seed": {"type": "number"}},
    )
    _create_question(
        fs,
        "/course/questions/not-magic",
        server_source="def generate(data):\n    pass\n",
    )

    assert main(["/course/questions"]) == 0

    first_output = Path(
        "/course/questions/algebra/addition/__plmagic_types__.py"
    )
    second_output = Path(
        "/course/questions/calculus/derivative/__plmagic_types__.py"
    )
    third_output = Path(
        "/course/questions/statistics/aliased/__plmagic_types__.py"
    )
    assert capsys.readouterr().out.splitlines() == [
        str(first_output),
        str(second_output),
        str(third_output),
    ]
    assert first_output.read_text(encoding="utf-8") == (
        "# AUTOMATICALLY GENERATED BY PLMAGIC #\n\n"
        "from plutil.lenses import QuestionData\n\n"
        "from typing import Literal, TypedDict\n\n"
        "class Preferences(TypedDict):\n"
        "    mode: Literal['practice', 'exam']\n"
        '    """Default value: `\'practice\'`"""\n'
        "    showHints: bool\n"
        '    """Default value: `True`"""\n\n'
        "class Data(QuestionData[Preferences]):\n"
        "    pass\n"
    )
    assert second_output.is_file()
    assert third_output.is_file()
    assert not Path(
        "/course/questions/not-magic/__plmagic_types__.py"
    ).exists()


def test_cli_defaults_to_current_directory(
    fs: FakeFilesystem, capsys: pytest.CaptureFixture[str]
) -> None:
    question_path = "/course/questions/default-directory"
    _create_question(
        fs,
        question_path,
        server_source="@plmagic\ndef generate(data):\n    pass\n",
        preferences={"seed": {"type": "number"}},
    )
    os.chdir("/course")

    assert main([]) == 0

    output_path = Path(question_path) / "__plmagic_types__.py"
    assert output_path.is_file()
    assert capsys.readouterr().out.strip() == str(output_path)


def test_cli_reports_a_matching_question_without_info_json(
    fs: FakeFilesystem, capsys: pytest.CaptureFixture[str]
) -> None:
    fs.create_file(
        "/course/questions/broken/server.py",
        contents="@plmagic\ndef generate(data):\n    pass\n",
        create_missing_dirs=True,
    )

    with pytest.raises(SystemExit) as exc_info:
        main(["/course/questions"])

    assert exc_info.value.code == 2
    assert "no companion info.json" in capsys.readouterr().err


def test_package_main_runs_plmagic_type_generation(
    fs: FakeFilesystem, capsys: pytest.CaptureFixture[str]
) -> None:
    question_path = "/course/questions/package-main"
    _create_question(
        fs,
        question_path,
        server_source="@plmagic\ndef generate(data):\n    pass\n",
        preferences={"seed": {"type": "number"}},
    )

    assert package_main(["/course/questions"]) == 0

    output_path = Path(question_path) / "__plmagic_types__.py"
    assert output_path.is_file()
    assert capsys.readouterr().out.strip() == str(output_path)


def test_cli_ignores_unparsable_python_without_plmagic(
    fs: FakeFilesystem, capsys: pytest.CaptureFixture[str]
) -> None:
    _create_question(
        fs,
        "/course/questions/magic",
        server_source="@plmagic\ndef generate(data):\n    pass\n",
        preferences={"seed": {"type": "number"}},
    )
    fs.create_file(
        "/course/questions/legacy/server.py",
        contents="def generate(data):\n    unmatched = )\n",
        create_missing_dirs=True,
    )

    assert main(["/course/questions"]) == 0
    assert Path("/course/questions/magic/__plmagic_types__.py").is_file()
    assert "magic/__plmagic_types__.py" in capsys.readouterr().out


def test_cli_does_not_write_or_print_all_empty_types(
    fs: FakeFilesystem, capsys: pytest.CaptureFixture[str]
) -> None:
    question_path = "/course/questions/no-preferences"
    _create_question(
        fs,
        question_path,
        server_source="@plmagic\ndef generate(data):\n    pass\n",
    )

    assert main(["/course/questions"]) == 0
    assert capsys.readouterr().out == ""
    assert not Path(question_path, "__plmagic_types__.py").exists()


def test_cli_overwrites_and_prints_stale_empty_type_file(
    fs: FakeFilesystem, capsys: pytest.CaptureFixture[str]
) -> None:
    question_path = "/course/questions/stale"
    _create_question(
        fs,
        question_path,
        server_source="@plmagic\ndef generate(data):\n    pass\n",
    )
    output_path = Path(question_path, "__plmagic_types__.py")
    fs.create_file(str(output_path), contents="class StalePreference: ...\n")

    assert main(["/course/questions"]) == 0
    assert capsys.readouterr().out.strip() == str(output_path)
    generated_source = output_path.read_text(encoding="utf-8")
    assert "StalePreference" not in generated_source
    assert "class Preferences(TypedDict):\n    pass" in generated_source


def test_cli_reports_full_path_for_unparsable_plmagic_candidate(
    fs: FakeFilesystem, capsys: pytest.CaptureFixture[str]
) -> None:
    fs.create_file(
        "/course/questions/broken/server.py",
        contents="from plutil import plmagic\n\n@plmagic\ndef generate(data):\n    value = )\n",
        create_missing_dirs=True,
    )

    with pytest.raises(SystemExit) as exc_info:
        main(["/course/questions"])

    error = capsys.readouterr().err
    assert exc_info.value.code == 2
    assert "/course/questions/broken/server.py:5:13" in error
    assert "unmatched ')'" in error
    assert "value = )" in error
