import ast
import json
import keyword
import re
from collections import defaultdict
from collections.abc import Iterable
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from plutil.lenses import BaseQuestion

from .element_data import choice_builder_lenses

AUTOGEN_COMMENT = """# AUTOMATICALLY GENERATED BY PLMAGIC #"""
DEFAULT_TYPE_FILE_NAME = "__plmagic_types__.py"


@dataclass(slots=True, frozen=True)
class TypeSourceBuilder:
    imports: dict[str, set[str]] = field(default_factory=lambda: defaultdict(set))
    builders: list["DataclassSourceBuilder | AliasSourceBuilder"] = field(
        default_factory=list
    )

    def import_from(self, module: str, *names: str) -> None:
        """Add names to a ``from module import ...`` statement."""
        self.imports[module].update(names)

    def add(self, builder: "DataclassSourceBuilder | AliasSourceBuilder") -> None:
        """Append a block of Python source."""
        self.builders.append(builder)

    @property
    def has_content(self) -> bool:
        """Return whether any block declares something question-specific."""
        return any(builder.has_content for builder in self.builders)

    def build(self) -> str:
        """Build the complete source file without writing it."""
        imports = (
            f"from {module} import {', '.join(sorted(names))}"
            for module, names in sorted(self.imports.items())
            if names
        )
        return (
            "\n\n".join(
                (
                    AUTOGEN_COMMENT,
                    *imports,
                    *(builder.build() for builder in self.builders),
                )
            )
            + "\n"
        )

    def write(self, path: Path) -> None:
        """Write the built source file to *path*."""
        path.write_text(self.build(), encoding="utf-8")


@dataclass(slots=True, frozen=True)
class DataclassSourceBuilder:
    name: str
    bases: tuple[str, ...] = ()
    fields: list[tuple[str, str, str | None]] = field(default_factory=list)

    def add_field(self, name: str, type_name: str, default: str | None = None) -> None:
        """Add an annotated field to the class."""
        self.fields.append((name, type_name, default))

    @property
    def has_content(self) -> bool:
        """Return whether the class declares any fields."""
        return bool(self.fields)

    def build(self) -> str:
        """Build a standard annotated class declaration.

        A ``TypedDict`` whose keys are not all identifiers uses the functional
        syntax instead, since such keys cannot be written as annotations.
        """
        if not all(_is_identifier(name) for name, _, _ in self.fields):
            if self.bases != ("TypedDict",):
                raise ValueError(
                    f"{self.name} field names must be identifiers unless it is a TypedDict"
                )
            items = ", ".join(
                f"{name!r}: {type_name}" for name, type_name, _ in self.fields
            )
            return f"{self.name} = TypedDict({self.name!r}, {{{items}}})"

        bases = f"({', '.join(self.bases)})" if self.bases else ""
        field_sources: list[str] = []
        for name, type_name, default in self.fields:
            field_sources.append(f"    {name}: {type_name}")
            if default is not None:
                escaped_default = default.replace("\\", "\\\\").replace('"""', '\\"""')
                field_sources.append(f'    """Default value: `{escaped_default}`"""')
        body = "\n".join(field_sources)
        return f"class {self.name}{bases}:\n{body or '    pass'}"


@dataclass(slots=True, frozen=True)
class AliasSourceBuilder:
    """A module-level type alias assignment such as ``Name = Literal[...]``."""

    name: str
    value: str

    @property
    def has_content(self) -> bool:
        """Return ``True``; an alias is always question-specific."""
        return True

    def build(self) -> str:
        """Build the alias assignment."""
        return f"{self.name} = {self.value}"


def _is_identifier(name: str) -> bool:
    return name.isidentifier() and not keyword.iskeyword(name)


def _preference_type(preference: object) -> tuple[str, str | None]:
    type_str, default = "Any", None
    if isinstance(preference, dict):
        values = preference.get("enum")
        if isinstance(values, list) and values:
            type_str = f"Literal[{', '.join(map(repr, values))}]"
        else:
            type_str = {
                "string": "str",
                "number": "float",
                "boolean": "bool",
            }.get(str(preference.get("type")), "Any")

        default = preference.get("default")

    default_str = repr(default) if default is not None else None
    return type_str, default_str


def _add_preferences_type(builder: TypeSourceBuilder, info_json_path: Path) -> str:
    info = json.loads(info_json_path.read_bytes())
    schema = info.get("preferences", {})
    if not isinstance(schema, dict):
        schema = {}
    preference_fields = [
        (name, *_preference_type(preference)) for name, preference in schema.items()
    ]
    builder.import_from("typing", "TypedDict")
    for type_name in {type_name for _, type_name, _ in preference_fields}:
        if type_name == "Any":
            builder.import_from("typing", "Any")
        elif type_name.startswith("Literal["):
            builder.import_from("typing", "Literal")
    preferences = DataclassSourceBuilder("Preferences", ("TypedDict",))
    preferences.fields.extend(preference_fields)
    builder.add(preferences)
    return preferences.name


def _add_custom_data_type(
    builder: TypeSourceBuilder, preferences_type_name: str
) -> None:
    builder.import_from("plutil.lenses", "BaseData")
    builder.add(DataclassSourceBuilder("Data", (f"BaseData[{preferences_type_name}]",)))


@dataclass(slots=True)
class ChoiceTags:
    """Statically discovered tags for one choice element.

    Attributes:
        lens: The lens class registered for the builder's element.
        tags: Literal tags in first-seen order.
        complete: Whether every contributing builder call was fully static.
    """

    lens: type[BaseQuestion[Any]]
    tags: dict[str, None] = field(default_factory=dict)
    complete: bool = True


def _callee_name(node: ast.expr) -> str | None:
    """Return the final name of ``f``, ``m.f``, or ``f[T]``."""
    if isinstance(node, ast.Subscript):
        node = node.value
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        return node.attr
    return None


def _literal_str(node: ast.expr | None) -> str | None:
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    return None


def _builder_tags(call: ast.Call) -> list[str] | None:
    """Return a builder call's literal tags, or ``None`` if they are not static."""
    tags: list[str] = []
    for arg in call.args:
        if _literal_str(arg) is not None:
            continue
        if not isinstance(arg, ast.Call) or _callee_name(arg.func) != "Choice":
            return None
        if any(kw.arg is None for kw in arg.keywords):
            return None
        tag_node = next((kw.value for kw in arg.keywords if kw.arg == "tag"), None)
        if tag_node is None:
            continue
        tag = _literal_str(tag_node)
        if tag is None:
            return None
        tags.append(tag)
    return tags


def collect_choice_tags(sources: Iterable[Path]) -> dict[str, ChoiceTags]:
    """Find ``ChoiceSet.store`` calls and their literal tags without executing code.

    Recognizes ``multiple_choice(...).store(data, "name")`` and the same call
    through a variable assigned exactly once to a builder call. Answers whose
    options are built dynamically are reported as incomplete.
    """
    builder_lenses = choice_builder_lenses()
    found: dict[str, ChoiceTags] = {}
    for source in sources:
        text = source.read_text(encoding="utf-8")
        if ".store(" not in text:
            continue
        try:
            tree = ast.parse(text, filename=str(source))
        except SyntaxError:
            continue

        assigned: dict[str, list[ast.expr]] = defaultdict(list)
        for node in ast.walk(tree):
            if isinstance(node, ast.Assign):
                for target in node.targets:
                    if isinstance(target, ast.Name):
                        assigned[target.id].append(node.value)
            elif (
                isinstance(node, ast.AnnAssign)
                and isinstance(node.target, ast.Name)
                and node.value is not None
            ):
                assigned[node.target.id].append(node.value)

        for node in ast.walk(tree):
            if not (
                isinstance(node, ast.Call)
                and isinstance(node.func, ast.Attribute)
                and node.func.attr == "store"
            ):
                continue
            receiver = node.func.value
            if isinstance(receiver, ast.Name) and len(assigned[receiver.id]) == 1:
                receiver = assigned[receiver.id][0]
            if not isinstance(receiver, ast.Call):
                continue
            lens = builder_lenses.get(_callee_name(receiver.func) or "")
            if lens is None:
                continue
            answers_node = node.args[1] if len(node.args) > 1 else None
            answers_node = next(
                (kw.value for kw in node.keywords if kw.arg == "answers_name"),
                answers_node,
            )
            answers_name = _literal_str(answers_node)
            if answers_name is None:
                continue

            entry = found.setdefault(answers_name, ChoiceTags(lens))
            tags = _builder_tags(receiver)
            if entry.lens != lens or tags is None:
                entry.complete = False
                continue
            entry.tags.update(dict.fromkeys(tags))
    return found


def _alias_stem(answers_name: str) -> str:
    stem = "".join(
        part[0].upper() + part[1:]
        for part in re.split(r"[^0-9A-Za-z]+", answers_name)
        if part
    )
    return stem if stem and not stem[0].isdigit() else f"Answer{stem}"


def _add_choice_tag_types(
    builder: TypeSourceBuilder, choice_tags: dict[str, ChoiceTags]
) -> None:
    taken = {"Data", "Preferences"}
    for answers_name, entry in sorted(choice_tags.items()):
        if not entry.complete or not entry.tags:
            continue
        stem = _alias_stem(answers_name)
        suffix = 1
        while {f"{stem}Tag", f"{stem}Question"} & taken:
            suffix += 1
            stem = f"{_alias_stem(answers_name)}{suffix}"
        taken |= {f"{stem}Tag", f"{stem}Question"}

        builder.import_from("typing", "Literal")
        builder.import_from(entry.lens.__module__, entry.lens.__name__)
        builder.add(
            AliasSourceBuilder(
                f"{stem}Tag", f"Literal[{', '.join(map(repr, entry.tags))}]"
            )
        )
        builder.add(
            AliasSourceBuilder(f"{stem}Question", f"{entry.lens.__name__}[{stem}Tag]")
        )


def write_plmagic_types_file(
    info_json_path: Path, path_name: str = DEFAULT_TYPE_FILE_NAME
) -> bool:
    """Write useful generated types, or refresh an existing stale type file.

    Choice tags come from the Python files beside ``info.json``; see
    :func:`collect_choice_tags`.
    """
    builder = TypeSourceBuilder()
    preferences_type = _add_preferences_type(builder, info_json_path)
    _add_custom_data_type(builder, preferences_type)
    sources = sorted(
        path for path in info_json_path.parent.glob("*.py") if path.name != path_name
    )
    _add_choice_tag_types(builder, collect_choice_tags(sources))
    output_path = info_json_path.parent / path_name
    if not builder.has_content and not output_path.exists():
        return False
    builder.write(output_path)
    return True
