import json
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path

AUTOGEN_COMMENT = """# AUTOMATICALLY GENERATED BY PLMAGIC #"""


@dataclass(slots=True, frozen=True)
class TypeSourceBuilder:
    imports: dict[str, set[str]] = field(default_factory=lambda: defaultdict(set))
    builders: list["DataclassSourceBuilder"] = field(default_factory=list)

    def import_from(self, module: str, *names: str) -> None:
        """Add names to a ``from module import ...`` statement."""
        self.imports[module].update(names)

    def add(self, builder: "DataclassSourceBuilder") -> None:
        """Append a block of Python source."""
        self.builders.append(builder)

    def build(self) -> str:
        """Build the complete source file without writing it."""
        imports = (
            f"from {module} import {', '.join(sorted(names))}"
            for module, names in sorted(self.imports.items())
            if names
        )
        return (
            "\n\n".join(
                (
                    AUTOGEN_COMMENT,
                    *imports,
                    *map(DataclassSourceBuilder.build, self.builders),
                )
            )
            + "\n"
        )

    def write(self, path: Path) -> None:
        """Write the built source file to *path*."""
        path.write_text(self.build(), encoding="utf-8")


@dataclass(slots=True, frozen=True)
class DataclassSourceBuilder:
    name: str
    bases: tuple[str, ...] = ()
    fields: list[tuple[str, str, str | None]] = field(default_factory=list)

    def add_field(self, name: str, type_name: str, default: str | None = None) -> None:
        """Add an annotated field to the class."""
        self.fields.append((name, type_name, default))

    def build(self) -> str:
        """Build a standard annotated class declaration."""
        bases = f"({', '.join(self.bases)})" if self.bases else ""
        default_suffix = lambda d: f" = {d}" if d is not None else ""
        body = "\n".join(
            f"    {name}: {type_name}{default_suffix(default)}"
            for name, type_name, default in self.fields
        )
        return f"class {self.name}{bases}:\n{body or '    pass'}"


def _preference_type(preference: object) -> tuple[str, str | None]:
    type_str, default = "Any", None
    if isinstance(preference, dict):
        values = preference.get("enum")
        if isinstance(values, list) and values:
            type_str = f"Literal[{', '.join(map(repr, values))}]"
        else:
            type_str = {
                "string": "str",
                "number": "float",
                "boolean": "bool",
            }.get(str(preference.get("type")), "Any")

        default = preference.get("default")

    default_str = repr(default) if default is not None else None
    return type_str, default_str


def _add_preferences_type(builder: TypeSourceBuilder, info_json_path: Path) -> str:
    info = json.loads(info_json_path.read_bytes())
    schema = info.get("preferences", {})
    if not isinstance(schema, dict):
        schema = {}
    preference_fields = [
        (name, *_preference_type(preference)) for name, preference in schema.items()
    ]
    builder.import_from("typing", "TypedDict")
    for type_name in {type_name for _, type_name, _ in preference_fields}:
        if type_name == "Any":
            builder.import_from("typing", "Any")
        elif type_name.startswith("Literal["):
            builder.import_from("typing", "Literal")
    preferences = DataclassSourceBuilder("Preferences", ("TypedDict",))
    preferences.fields.extend(preference_fields)
    builder.add(preferences)
    return preferences.name


def _add_custom_data_type(
    builder: TypeSourceBuilder, preferences_type_name: str
) -> None:
    builder.import_from("plutil.lenses", "QuestionData")
    builder.add(
        DataclassSourceBuilder("Data", (f"QuestionData[{preferences_type_name}]",))
    )


def write_plmagic_types_file(
    info_json_path: Path, path_name: str = "__plmagic_types__.py"
) -> None:
    builder = TypeSourceBuilder()
    preferences_type = _add_preferences_type(builder, info_json_path)
    _add_custom_data_type(builder, preferences_type)
    builder.write(info_json_path.parent / path_name)
